# Generated by Django 4.1.1 on 2022-09-19 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("stripepay", "0002_item_name_stripe"),
    ]

    operations = [
        migrations.RenameField(
            model_name="item",
            old_name="name_stripe",
            new_name="price_stripe",
        ),
    ]
